# Generated by Django 5.0 on 2023-12-11 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_feeding"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feeding",
            old_name="cat",
            new_name="finch",
        ),
    ]
